services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_PASSWORD}
    ports:
      - 1433:1433
    volumes:
      - ./data/sqlserver:/var/opt/mssql/data
      - ./scripts/sqlserver/init.sql:/usr/local/bin/init.sql
      - ./scripts/sqlserver/entrypoint.sh:/usr/local/bin/entrypoint.sh
    entrypoint: ["/bin/bash", "/usr/local/bin/entrypoint.sh"]
    networks:
      - book-network

  api:
    build:
      context: ./Back/DotNet/API
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DevConnection=${ConnectionStrings__DevConnection_Docker}
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - book-network
    volumes:
      - ./Back:/src/API
    command: dotnet watch run --urls http://0.0.0.0:80

  react:
    build:
      context: ./Front/ReactJS
      dockerfile: Dockerfile
    container_name: react
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    volumes:
      - ./Front/ReactJS:/app
      - ./scripts:/scripts:ro
      - ./.env:/env/.env:ro
    depends_on:
      - api
    networks:
      - book-network
    command: sh -c "node /scripts/sync-react-env.js && npm run dev"

networks:
  book-network: