# Use Node.js as the base image
FROM node:20.3.1-bullseye-slim

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Remove node_modules if they exist and install dependencies
RUN rm -rf node_modules
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port 4200
EXPOSE 4200

# Start the Angular application in watch mode
CMD ["npm", "start"]
